services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: aruda_presence_dev
    ports:
      - "${APP_PORT:-8180}:8000"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    command: composer dev
    depends_on:
      - db
    restart: always

  db:
    image: mysql:9.0
    container_name: aruda_presence_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=presence_db
      - MYSQL_USER=presence_user
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
